//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phones()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int Id_Phone { get; set; }
        public string NamePhone { get; set; }
        public int Id_MaterialPhone { get; set; }
        public int Id_TypePhone { get; set; }
        public int Id_TypeErrors { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual MaterialPhone MaterialPhone { get; set; }
        public virtual TypeErrors TypeErrors { get; set; }
        public virtual TypePhone TypePhone { get; set; }
    }
}
